apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   app: az-aks-challenge
   component: eventlistener
 name: eventlistner
spec:
 replicas: 1
 selector:
   matchLabels:
     app: az-aks-challenge
     component: eventlistener
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 template:
   metadata:
     creationTimestamp: null
     labels:
       app: az-aks-challenge
       component: eventlistener
   spec:
     containers:
     - env:
       - name: TEAMNAME
         value: honey-badgers
       - name: EVENTHUBCONNSTRING
         value: Endpoint=sb://k8-hack-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Ws9MR7LQNzHy1xEpfzjZ5zkl/uuZ/QlihXRqARu4IsQ=
       - name: EVENTHUBPATH
         value: k8-hack-eventhub
       - name: PROCESSENDPOINT
         value: http://fulfillorder:8080/v1/order/
       image: outsurance.azurecr.io/eventhublistenerack
       imagePullPolicy: Always
       name: eventlistener
     imagePullSecrets:
     - name: az-aks-challenge
---
apiVersion: v1
kind: Service
metadata:
 name: eventlistener
spec:
 ports:
 - port: 80
   targetPort: 80
 selector:
   app: az-aks-challenge
   component: eventlistener
 type: ClusterIP
